draft-iyengar-quic-delayed-ack.md
This PR changes a few things:
- Introduces a `min_ack_delay` TP for negotiating extension use
- Changes `Time Tolerance` to `Update Max Ack Delay`
- Makes the fields required
- Specifies invalid values
Closes #2.
=> Change Time Tolerance to Update Max Ack Delay

draft-iyengar-quic-delayed-ack.md
Fixes #14  by removing references to slow start, hystart, and paced chirping.
Slow start and BBR startup aren't quite the same as @mjoras mentioned, hystart isn't specified for QUIC, and paced chirping is not an IETF draft to my knowledge.
=> Remove mention of slow start and hystart

draft-iyengar-quic-delayed-ack.md
If there's a frame with a larger sequence number, there's no need to retransmit.
=> Clarify when you might not retransmit

draft-iyengar-quic-delayed-ack.md
Use TRANSPORT_PARAMETER_ERROR for communicating errors in TP, rather than using PROTOCOL_VIOLATION.
=> use TRANSPORT_PARAMETER_ERROR

draft-iyengar-quic-delayed-ack.md
At the moment, the specification requires the use of FRAME_ENCODING_ERROR when an endpoint receives an ACK_FREQUENCY frame with the value of Update Max Ack Delay field being smaller than `min_ack_delay`.
That contradicts from the practice of the core draft, that restricts the use of FRAME_ENCODING_ERROR to syntactic (i.e. encoding) errors.
This PR fixes the problem by changing the error code to be used in that case to PROTOCOL_VIOLATION.
=> follow the practice of using PROTOCOL_VIOLATION for semantic errors

draft-iyengar-quic-delayed-ack.md
We don't need to change the frame type on each draft version, but I figured that it'd be safer.
=> Change codepoints to avoid conflict with draft revisions

draft-iyengar-quic-delayed-ack.md
Fixes #42. Clearly declares that the TP only works in one direction.
=> min_ack_delay is a unilateral indication

draft-ietf-quic-ack-frequency.md
Part of #27
We still need to decide whether to change 'Update Max Ack Delay' to 'Max Ack Delay'.
=> Rename 'Packet Tolerance' to 'ACK-Eliciting Threshold'

draft-ietf-quic-ack-frequency.md
=> Cap ACK-eliciting threshold if the received value is too large

draft-ietf-quic-ack-frequency.md
Fixes #49
Also updates the transport parameter codepoint to 0xff03de1a from 0xff02de1a.
=> Tweak ack-eliciting threshold.

draft-ietf-quic-ack-frequency.md
Fixes #37 by allowing implementations to not add max_ack_delay to the PTO calculation if enough ack-eliciting packets are in flight.
=> MAY omit the max_ack_delay if enough packets are in flight

draft-ietf-quic-ack-frequency.md
Closes #22 and #40
And by implication, cannot send ACK_FREQUENCY in 0-RTT packets.
=> MUST NOT store min_ack_delay

draft-ietf-quic-ack-frequency.md
Provides more details on why excluding max_ack_delay when Ignore Order is used may cause premature PTOs.
Fixes #110
=> Ignore Order and excluding max_ack_delay

draft-ietf-quic-ack-frequency.md
We have normative text for Ignore Order, but none for Ignore CE.
SHOULD NOT use with ECN(1) marking per L4S or DCTCP.
Fixes #107 
Fixes #109
=> Add normative text for 'Ignore CE'

draft-ietf-quic-ack-frequency.md
Also moves text about batch processing of packets into an existing section.
Fixes #132
=> Remove 'bundle'

draft-ietf-quic-ack-frequency.md
This PR makes the text shorter and tightens the normative requirements around handling of multple ACK_FREQUENCY frames. This PR makes one normative change: Sequence Number value is no longer required to start at zero.
=> Alternative PR to add MUSTs in multiple-frame section

draft-ietf-quic-ack-frequency.md
MUSTs become SHOULD to align better with ACK behavior test in RFC9000.
=> Unify normative language on Reordering Threshold

draft-ietf-quic-ack-frequency.md
Fixes #106
Removes the normative SHOULD from: "a sender SHOULD cause a receiver to send an acknowledgement at least once per RTT if there are unacknowledged ack-eliciting packets in flight". It may be added back in some form, see issue #147
=> Update Congestion Control section

draft-ietf-quic-ack-frequency.md
Fixes #140 and provides two simple examples
Written as an alternative to #143
=> Rewrite 'Response to Out-of-Order Packets'

draft-ietf-quic-ack-frequency.md
This clarification is not necessarily needed but I think it would help me. Just a proposal...
=> Clarification on ACK sending after an reordering ACK was sent

draft-ietf-quic-ack-frequency.md
The examples are unclear, because they're not on separate lines.
=> Fix formatting of Examples

draft-ietf-quic-ack-frequency.md
=> Delete unnecessary paragraph about batching ACKs

draft-ietf-quic-ack-frequency.md
Fixes #163
This adds a SHOULD, but it seems sensible given the implications on PTO.
=> Clarify 'it'

draft-ietf-quic-ack-frequency.md
The wire format changed to include a new Reordering Threshold field.
In order for different draft versions to coexist, we should change the Transport Param codepoint for min_ack_delay
Fixes #162
=> Update the transport param codepoint

draft-ietf-quic-ack-frequency.md
We had similar text in the two sections, and the latter one was where the SHOULD was, so this consolidates the duplicate text into the Congestion Control section.
This is intended as an editorial cleanup prior the the PR for #168
=> Editorial Pass on Congestion Control and Loss Detection

draft-ietf-quic-ack-frequency.md
=> change error code to TRANSPORT_PARAMETER_ERROR

draft-ietf-quic-ack-frequency.md
I believe this is backwards.  The important thing is that if the sender of the ACK_FREQUENCY frame doesn't use the new, smaller ack delay for PTO until it's certain the peer has received it.
=> Decreases the peer's max_ack_delay

draft-ietf-quic-ack-frequency.md
Given the specified Reordering Threshold.
This is possible either when the delayed ACK timer or the Ack-Eliciting Threshold causes an ACK to be sent before the packet can be declared immediately lost, but with a higher Largest Acked than the missing packet.
Fixes #213
Closes #219
=> Send an immediate ACK when loss can be detected

draft-ietf-quic-ack-frequency.md
The term "acknowledgment packet" is used only twice in the Introduction (in the form that omits "E"). Neither of them talks specifically about ACK-only frames.
=> Remove definition of a term that is essentially unused

draft-ietf-quic-ack-frequency.md
At the moment, the specification sounds as if a duplicate ACK_FREQUENCY frame has to be processed.
This is a nitpick, so I would not mind it being closed.
=> process each ACK_FREQUENCY frame only once

draft-ietf-quic-ack-frequency.md
Section 3:
> Receiving a min_ack_delay transport parameter indicates that the peer might send ACK_FREQUENCY frames in the future.  Until an ACK_FREQUENCY frame is received, receiving this transport parameter does not cause the endpoint to change its acknowledgement behavior.
This paragraph is confusing.
They sound as if the receiver of min_ack_delay TP also receives the ACK_FREQUENCY frame.
The PR removes the first sentence, because it is verbose in addition to being confusing. The paragraph right above states that "the sender of min_ack_delay TP must be prepared to receive ACK_FREQUENCY frame."
Also, the PR changes the verb of the second sentence from "receiving" to "sending" to reflect the roles correctly.
=> sender of min_ack_delay changes the ack behavior

draft-ietf-quic-ack-frequency.md
=> abstract and intro

draft-ietf-quic-ack-frequency.md
Alternative to #265.
Fixes #224
=> Clarify motivations

draft-ietf-quic-ack-frequency.md
=> how to request one ack per rtt

draft-ietf-quic-ack-frequency.md
=> change CE behaviour only when threshold > 1

draft-ietf-quic-ack-frequency.md
This adds tables that show each variables when a packet is received for out-of-order packet examples.  This would clarify what happens exactly for each packet reception and how algorithm works.
This clarifies my own comment at https://github.com/quicwg/ack-frequency/issues/248#issuecomment-1880749218
This might be redundant, but it would help understanding how algorithm works.
=> Add tables to describe each variables for out-of-order examples

draft-ietf-quic-ack-frequency.md
Possibly we should rename this to "Advertising Extension Support" or something similar as well, since I'm not sure I'd consider this unilateral advertisement approach 'negotiating'?
=> Tweak Negotiating Extension Use

draft-ietf-quic-ack-frequency.md
=> Gorry's editorial comments

draft-ietf-quic-ack-frequency.md
fixes issue #310
This was agreed and added in PR #136 but, I believe by mistake, removed in editorial pass in PR #160.
=> Re-add sentence that IMMEDIATE_ACK does not need to be retransmitted.

draft-ietf-quic-ack-frequency.md
=> Clarify Ack-Eliciting Threshold of 0 and 1

draft-ietf-quic-ack-frequency.md
fixes #305
I look at this multiple times and also checked with Ian. Not sure how this happened but we must have missed something at some point. I provide his change now which should also align with RFC9002, as @michael-eriksson pointed out.
=> fix 1-off error in definition and example

draft-ietf-quic-ack-frequency.md
Upon receipt of a previously missing packet.
This is an alternative to #318 that reuses Largest Acked.
Fixes #304
=> When to send an immediate ACK

draft-ietf-quic-ack-frequency.md
Adding milliseconds here makes it clear that the values above 2^14 _milliseconds_ are invalid. The distinction helps because the field is in microseconds, but the limit and reference are in milliseconds.
=> add unit for clarity
