draft-iyengar-quic-delayed-ack.md
=> Add section on PTO computation with updated max_ack_delay

draft-iyengar-quic-delayed-ack.md
=> Add sequence number to frame

draft-iyengar-quic-delayed-ack.md
=> Handle initial conditions

draft-iyengar-quic-delayed-ack.md
=> Add reordering tolerance

draft-iyengar-quic-delayed-ack.md
Plus fixing one spot where it said 2^14, but I think it should have been 2^24
=> Editorial comments

draft-iyengar-quic-delayed-ack.md
Changed the error code to FRAME_ENCODING_ERROR and removed a condition for update which I think may end up causing correctness issues.
=> A few more suggestions

draft-iyengar-quic-delayed-ack.md
=> Editorial for undesirable consequence

draft-iyengar-quic-delayed-ack.md
=> Re-introduce text that was inadvertently removed

draft-iyengar-quic-delayed-ack.md
Also rename ACK-FREQUENCY to ACK_FREQUENCY to Fix #19
=> Define codepoints for the transport param and frame

draft-iyengar-quic-delayed-ack.md
=> Use frame instead of TP for reordering

draft-iyengar-quic-delayed-ack.md
=> 0 is a valid min_ack_delay

draft-iyengar-quic-delayed-ack.md
I think the motivations section as-is is too long. It spends a lot of time
talking about what are effectively the tradeoffs. IMO the motivations section
should specify why it's useful to have the sender control the receiver's ACK
frequency, and then we can have a separate section for the tradeoffs.
This takes a stab at that section, lifting things from motivations and adding
some new text specifically addressing the nascent stages of a connection. 
I also made some editorial changes to the existing text.
I am happy to add any additional considerations we think might need to be called out.
This attempts to resolve #17
=> Remove sections from motivations, add implementation considerations.

draft-ietf-quic-ack-frequency.md
Copy of #39, applied to new draft filename.
Closes #39.
=> Fix CE section reference

draft-ietf-quic-ack-frequency.md
=> Set limits to min_ack_delay and max_ack_delay

draft-ietf-quic-ack-frequency.md
Fixes the remainder of #27 not fixed by #55
=> Change Update Max Ack Delay to Request Max Ack Delay

draft-ietf-quic-ack-frequency.md
=> Don't change ack behavior until ACK_FREQUENCY is received

draft-ietf-quic-ack-frequency.md
=> Use RFC9000 frame formats

draft-ietf-quic-ack-frequency.md
=> Remove simply

draft-ietf-quic-ack-frequency.md
=> Don't use 'Generally'

draft-ietf-quic-ack-frequency.md
Closes #51
I tried to work in what I thought were the important parts of Gorry's suggested text, PTAL if I captured everything.
=> Update Motivation for Asymmetric Paths

draft-ietf-quic-ack-frequency.md
=> Remove 'Ignore CE'

draft-ietf-quic-ack-frequency.md
=> Change 'Ignore Order' to 'Reordering Threshold'

draft-ietf-quic-ack-frequency.md
fixes #104
originally created by @gorryfair in https://github.com/gorryfair/ack-frequency/commit/57ae17167548f2f5a550b05ffc2c8d0afaa85bc3 (but not PR was created)
=> Add reference to sec 14 of RFC9000 for PMTU probes

draft-ietf-quic-ack-frequency.md
=> Clarify use with PING frames

draft-ietf-quic-ack-frequency.md
=> send IMMEDIATE_ACK before idle period

draft-ietf-quic-ack-frequency.md
=> Clarify default reordering threshold and provide further recommendation

draft-ietf-quic-ack-frequency.md
This is an alternative to #128 with the intent of fixing #53
Closes #128
=> Add references to RFC 3449 and an Ack Frequency study

draft-ietf-quic-ack-frequency.md
=> SHOULD instead of MUST use values of ACK_FREQUENCY

draft-ietf-quic-ack-frequency.md
=> Text for security considerations

draft-ietf-quic-ack-frequency.md
Another attempt to fix #154 
Removes an unnecessary MUST.
=> Burst Mitigation v2

draft-ietf-quic-ack-frequency.md
I'm assuming I should add myself as author. If you think that not warrantable, that's fine as well. Just let me know.
=> Add Mirja as author

draft-ietf-quic-ack-frequency.md
=> Remove an unnecessary sentence and MUST

draft-ietf-quic-ack-frequency.md
=> Nits Gorry

draft-ietf-quic-ack-frequency.md
This seeks to address NiTs in the current revision, see related PR.
=> NiT resulotion suggestions for draft-ietf-quic-ack-frequency.md

draft-ietf-quic-ack-frequency.md
=> Add subsection to highlight application-limited cases

draft-ietf-quic-ack-frequency.md
=> Remove harmful for reordering threshold > 1

draft-ietf-quic-ack-frequency.md
This PR takes on the editorial changes from PR #201. The actual definition part of the recording threshold might need further discussion and clarification.
=> Editorial proposals by @huitema

draft-ietf-quic-ack-frequency.md
This is a much more minimal change than #210
Fixes #168.
Closes #210
=> Remove SHOULD from 1 ACK/RTT

draft-ietf-quic-ack-frequency.md
=> Recommend eliciting an ACK soon after idle

draft-ietf-quic-ack-frequency.md
From the discussion of #209 in the QUIC WG meeting
=> Recommend sending an ACK after a long period of idle

draft-ietf-quic-ack-frequency.md
=> Don't use Min RTT to set max_ack_delay

draft-ietf-quic-ack-frequency.md
=> Immediate ACKs are good for PTO

draft-ietf-quic-ack-frequency.md
=> Clarify frames are congestion controlled

draft-ietf-quic-ack-frequency.md
=> Acknowledgment not Acknowledgement

draft-ietf-quic-ack-frequency.md
=> ACK_FRAME -> ACK frame

draft-ietf-quic-ack-frequency.md
Fixes #236 
There was a request for clarification that it doesn't have to start at 0, but is that necessary?
=> Sequence number is monotonically increasing

draft-ietf-quic-ack-frequency.md
=> ACK_FREQUENCY frame not this frame

draft-ietf-quic-ack-frequency.md
=> Fix section references

draft-ietf-quic-ack-frequency.md
=> Use terms consistently

draft-ietf-quic-ack-frequency.md
=> no IMMEDIATE_ACK in 0RTT

draft-ietf-quic-ack-frequency.md
=> IMMEDIATE_ACK is part of this as well

draft-ietf-quic-ack-frequency.md
=> number maximum-sized packet in the cwnd

draft-ietf-quic-ack-frequency.md
=> Reference in sec 3 to new frames types

draft-ietf-quic-ack-frequency.md
=> add ref to RFC9000 21.9 in sec considerations

draft-ietf-quic-ack-frequency.md
=> Explain example further

draft-ietf-quic-ack-frequency.md
=> max value of max_ack_delay

draft-ietf-quic-ack-frequency.md
=> Clarify when to send ACK_FREQUENCY frame

draft-ietf-quic-ack-frequency.md
=> fix reference to RFC 9002

draft-ietf-quic-ack-frequency.md
=> apply RFC 9000 principles to error codes

draft-ietf-quic-ack-frequency.md
=> start with packet number 0 in examples

draft-ietf-quic-ack-frequency.md
=> Only send an ACK if Ack-eliciting packets have been received

draft-ietf-quic-ack-frequency.md
=> clarify that no batch process is assumed in examples.

.github/workflows/archive.yml, .github/workflows/ghpages.yml, .github/workflows/publish.yml, .github/workflows/update.yml
- **Automatic update of .github/workflows/ghpages.yml**
- **Automatic update of .github/workflows/publish.yml**
- **Automatic update of .github/workflows/archive.yml**
- **Automatic update of .github/workflows/update.yml**
=> make update-ci

draft-ietf-quic-ack-frequency.md
=> s/before/without sending an ACK
